import os

# Configuration
LOG_LEVEL = "DEBUG"
HTTP_RESPONSE_SUCCESS = "success"
HTTP_RESPONSE_FAILURE = "error"
MONGODB_URL = os.getenv("MONGODB_URL")



# Postgres Connection
POSTGRES_USERNAME = os.getenv("POSTGRES_USERNAME")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DATABASE_NAME = os.getenv("POSTGRES_DATABASE_NAME")
